### ISSUE TITLE
Please add support for delayed populate() when option.loading==True

### ISSUE THREAD

**Issue by nirgal** [xuanye/xgcalendar#24]
Hello again

I have a small issue when the user click "previous" quicker than the server sends the json: Sometimes the displayed month has no event displayed while there are some on the server.

The problem is with option.loading. populate() is careful not to send another request if the previous one is not complete. This is good since the number of simmulaneous requests is limited. This means that if the user click like a madman on "previous" button, some monthes will be skip. But sometimes, the current month is not displayed. The user must click "Refresh" manually. For exemple:

user ask for 2015-01
request for 2015-01 sent
answer for 2015-01 received (good)
user ask for 2014-12
request for 2014-12 sent
user ask for 2014-11
NO request for 2014-11 because isloading==True
answer for 2014-12 received

Here I have November 2014 displayed without the events.

One solution would be to try to have onAfterRequestData callback to check if request was made. But there, loading==True, so we cannot refresh.

I think I will try to have a timeOut callback as a work around. But I think that is a global xgcalendar problem and maybe you can think of a good solution?

One better possibility would be to store the last showdate used in populate() request, and run it asynchronously when previous request is complete:

1. Inside function populate(), if(loading) is true, then store the request as "busy_showdate". Maybe busy_showdate was null, maybe there already was a value. Anyways we store only the last one.

2. Inside function pupolate(), when $.ajax() returns, we look if "busy_showdate" is not null: If there is a value, we set it to null, and we run $ajax() immediatly or with a tiny timeout to make sure the xml request is closed, otherwise we set loading = False.

Do you think it's a good idea?

It's very difficult to fix outside of xgcalendar core...

**Comment by xuanye** [comment]
i think  : check the `option.isloading`  in click event handler funciton will be better.

**Comment by nirgal** [comment]
Do you mean in the user defined onAfterRequestData ?
This is very difficult because populate() returns immediately when isloading is True. It would require for each application to save the requests state.

I'm not sure I understand you.
This a a minor issue, but it's quite difficult to fix properly.
I believe everyone using xgcalendar will be affacted, and this is easier to fix on the global side.

I'll work on a patch today.

**Comment by xuanye** [comment]
我不知道你是否能看懂中文，但是我也不确定我是否能够准确地用英文表达我的意思，
我觉得应该在页面上调用视图切换/前进/后退的事件中通过`$.fn.BcalGetOp` 获取option来判断`option.isloading` ，这样可以更好的和界面的其他元素互动，比如实例中小的minical.

i mean: u should call $.fn.BcalGetOp , get the option and check `option.isloading` in your click event (which event will call view switch /prev day/next day ,etc.

**Comment by nirgal** [comment]
Hi Xuanye Wang

Bug summary:
When you double-click on `previous` in month view, then the interface go backward twice, and the second month is empty.
If you cannot reproduce it, maybe you can add a small delay in the server to see it. I mean like adding a "sleep(1 second)" before answering.
This is because populate does nothing if another request is not finished.

"options.isloading" is always true inside the user callbacks. So it is not possible to activate a trigger to change showday there.

It is technically possible to check "BcalGetOp().isloading" before activating a change. But this is bad: 
If the user double click on previous, then the second click is refused and discarded when the calendar is busy.
Moreover, if you have a mini-calalendar elsewhere that tries to synchronize with the main page, then it means the main page will sometimes refuse. It means that the developper has to make a system to check going to previous month is authorized in the mini-calendar.

With my patch, you can give orders to the main calendar. Sometimes it will be delayed because it is busy with another request. But it will shortly catch up with the requests.
Don't you think it is much better?

If you don't want xgcalendar to be slow, you need to act as soon as the pending request is finished. You don't want the user to try again.
The problem is that you cannot do that in the callback provided by xgcalendar because "options.isloading" is always true there.

It would be possible to modify xgcalendar to set "options.isloading=False" before calling onAfterRequestData or onRequestDataError. That would improve things.
But I believe my solution is better because every user would want xgcalendar to automatically load the month they requested.

-----------------------
This is an automatic translation using https://translate.google.com :

喜选冶王

漏洞概要：
当您在`previous`在月视图双击，然后界面倒退两次，第二个月是空的。
如果你不能重现它，也许你可以在服务器添加一个小的延迟才能看到它。我的意思是像回答之前增加一个“睡眠（1秒）”。
这是因为填充什么也不做，如果其他请求没有完成。

“options.isloading”始终是用户回调里面真。所以这是不可能激活触发器改变showday那里。

这在技术上是可以检查“BcalGetOp（）。isloading”激活更改之前。但是，这是不好的：
如果用户双击以前的，那么第二次点击被拒绝，当日历忙丢弃。
此外，如果你有一个小型calalendar其他地方，试图与主网页同步，那么就意味着在主网页有时会拒绝。这意味着，开发商必须作出一个系统检查将较前期被授权在迷你日历。

与我的补丁，你可以到主日历发号施令。有时它会被延迟，因为它正忙于另一个请求。但它会在短期内赶上的请求。
难道你不认为这是更好？

如果你不想xgcalendar是缓慢的，需要尽快挂起的请求完成后采取行动。你不希望用户再试一次。
问题是，你不能这样做，在由xgcalendar提供的回调，因为“options.isloading”始终是真实的存在。

这将有可能修改xgcalendar主叫onAfterRequestData或onRequestDataError之前设置“options.isloading =假”。这将改善的事情。
但我相信我的解决方案是更好的，因为每一个用户都希望xgcalendar自动加载他们要求的一个月。

**Comment by billzw** [comment]
东西不错。
